services:
  - type: web
    name: marco-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Marco_backend:app
    envVars:
      - key: PYTHON_PORT
        value: 10000
      - key: MONGO_URI
        sync: false # You'll need to set this in Render's dashboard
    autoDeploy: true
